# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Template-Plugin-Number-Format
version:      1.02
version_from: Format.pm
installdirs:  site
requires:
    Number::Format:                0
    Template:                      2.07

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
